---
title: " "
output:
   html_document:
     css: style.css
---

<p align = "justify">

<font size="5"> Data analysis for: </font>

<font size="4"> Graham ZA and Padilla Perez DJ, (2023). Correlated evolution between body color and burrowing behavior in crayfish.</font>
</p>

</p></p>

[Dylan J. Padilla Perez](https://dylanpadilla.netlify.app/), School of Life Sciences, Arizona State University, Tempe, AZ 85287, USA.
</p></p>

<b>
<font size="4"> Library </font>
</b>


```{r, include = FALSE}

knitr::opts_chunk$set(comment = ">", fig.width = 7, fig.height = 7, dpi = 300, warning = FALSE)

```


```{r}

library(phytools)
library(ape)
library(caper)
library(geiger)
library(ggtree)
library(ggtreeExtra)
library(ggplot2)
library(plotrix)
library(png)
library(xtable)

```

```{r}

R.version
sessionInfo()

```

</br></br></br>


<font size="4"> **Evolution of coloration in crayfish** </font>

</br>

```{r}

## Loading data

craydata <- read.csv("col_data.csv", row.names = 1)
head(craydata)

craytree <- read.tree("stern.2017.ml.new.tree")
craytree

## Changing levels of the factors "body_color" and "combined_burrow_category" for modeling discrete traits

craydata$body_color[craydata$body_color == "no"] <- "cryptic"
craydata$body_color[craydata$body_color == "blue"] <- "conspicuous"
craydata$body_color[craydata$body_color == "orange"] <- "conspicuous"
craydata$body_color[craydata$body_color == "purple"] <- "conspicuous"
craydata$body_color[craydata$body_color == "red"] <- "conspicuous"
craydata$body_color[craydata$body_color == "blue_red"] <- "conspicuous"
craydata$body_color[craydata$body_color == "orange_red"] <- "conspicuous"
craydata$body_color[craydata$body_color == "blue_orange_red"] <- "conspicuous"
craydata$body_color[craydata$body_color == "blue_purple"] <- "conspicuous"
craydata$body_color[craydata$body_color == "unpigmented"] <- "cryptic"

craydata$species <- rownames(craydata)
names(craydata)

craydata <- craydata[ , c(19, 1:18)]

unique(craydata$body_color)

craydata$body_color <- as.factor(craydata$body_color)
levels(craydata$body_color)

unique(craydata$combined_burrow_category)

craydata$combined_burrow_category[craydata$combined_burrow_category == "terrestrial_burrower"] <- "semi-terrestrial"
craydata$combined_burrow_category[craydata$combined_burrow_category == "aquatic_burrower"] <- "aquatic"

craydata$combined_burrow_category <- as.factor(craydata$combined_burrow_category)
levels(craydata$combined_burrow_category)


## Pruning the data and tree

chk <- name.check(craytree, craydata)
summary(chk)

pruned.tree <- drop.tip(craytree, chk$tree_not_data)
pruned.data <- craydata[!(rownames(craydata) %in% chk$data_not_tree),, drop = FALSE]
name.check(pruned.tree, pruned.data)

bodycol <- setNames(as.factor(pruned.data$body_color), rownames(pruned.data))
head(bodycol)
burrowing <- setNames(as.factor(pruned.data$combined_burrow_category), rownames(pruned.data))
head(burrowing)


## Fitting models of correlated evolution

interdependent.model <- fitPagel(pruned.tree, bodycol, burrowing)
print(interdependent.model)
dependent.bodycol <- fitPagel(pruned.tree, bodycol, burrowing, dep.var = "y")
print(dependent.bodycol)
dependent.burrowing <- fitPagel(pruned.tree, bodycol, burrowing, dep.var = "x")
print(dependent.burrowing)


anova(dependent.burrowing, dependent.bodycol, interdependent.model)

##xtable(anova(dependent.burrowing, dependent.bodycol, interdependent.model), digits = 3)


## Plotting model

plot(dependent.bodycol, fit.signif = 4, cex.main = 1,
     cex.sub = 0.8, cex.traits = 0.7, color = TRUE,
     cex.rates = 0.7, lwd = 1, lwd.by.rate = TRUE, max.lwd = 4)


```


```{r, include = FALSE}

## Plotting model

png("figure1.png", height = 7, width = 7, units = "in", res = 300)

## pdf("figure1.pdf")

plot(dependent.bodycol, fit.signif = 4, cex.main = 1,
     cex.sub = 0.8, cex.traits = 0.7, width = TRUE, color = TRUE,
     cex.rates = 0.7, lwd = 1, lwd.by.rate = TRUE, max.lwd = 4)

dev.off()


pdf("figure1.pdf")

plot(dependent.bodycol, fit.signif = 4, cex.main = 1,
     cex.sub = 0.8, cex.traits = 0.7, color = TRUE,
     cex.rates = 0.7, lwd = 1, lwd.by.rate = TRUE, max.lwd = 4)

dev.off()

```



```{r}

## Trees facing to each other

quartz()

layout(matrix(c(1, 1, 2, 2,
                1, 1, 3, 3,
                1, 1, 3, 3,
                1, 1, 2, 0,
                1, 1, 2, 2), nrow = 5, ncol = 4, byrow = TRUE))


c <- pruned.data$species[pruned.data$body_color == "c"]
cons <- pruned.data$species[pruned.data$body_color == "c*"]

## paint the edges

tt <- paintBranches(pruned.tree, edge = sapply(cons, match, pruned.tree$tip.label),
    state = "c*", anc.state = "c")

cols1 <- setNames(c("black", "orange"), c("c", "c*"))

## Body color tree

plot(tt, cols1, ftype = "off", lwd = 2, offset = 0.4)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(tt))

points(pp$xx[1:Ntip(tt)] + 0.02*h, pp$yy[1:Ntip(tt)], pch = 16,
    col = cols1[bodycol[tt$tip.label]], cex = 0.6)

legend("topleft", legend = c("cryptic", "conspicuous"), pch = 21, pt.bg = cols1,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)

cryptic <- readPNG("cryptic.png")
conspicuous <- readPNG("conspicuous.png")

rasterImage(cryptic, 65, 300, 170, 380)
rasterImage(conspicuous, 60, 213, 168, 295)


## Burrowing tree

a <- pruned.data$species[pruned.data$combined_burrow_category == "a"]
t <- pruned.data$species[pruned.data$combined_burrow_category == "t"]

## paint the edges

bt <- paintBranches(pruned.tree, edge = sapply(a, match, pruned.tree$tip.label),
    state = "a", anc.state = "t")

bt

cols2 <- setNames(c("#2F5597", "#956D45"), c("a", "t"))

## Burrowing tree

plot(bt, cols2, ftype = "off", lwd = 2, offset = 0.4, direction = "leftwards")
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(bt))

points(pp$xx[1:Ntip(bt)] - 0.02*h, pp$yy[1:Ntip(bt)], pch = 16,
   col = cols2[burrowing[bt$tip.label]], cex = 0.6)


legend("topright", legend = c("aquatic burrowing", "semi-terrestrial burrowing"), pch = 21, pt.bg = cols2,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)


burrow <- readPNG("burrow3.png")

rasterImage(burrow, 70, 220, 260, 380)

```


```{r, include = FALSE}


## Trees facing to each other

png("figure2.png", height = 7, width = 7, units = "in", res = 300)

layout(matrix(c(1, 1, 2, 2,
                1, 1, 3, 3,
                1, 1, 3, 3,
                1, 1, 2, 0,
                1, 1, 2, 2), nrow = 5, ncol = 4, byrow = TRUE))


c <- pruned.data$species[pruned.data$body_color == "c"]
cons <- pruned.data$species[pruned.data$body_color == "c*"]

## paint the edges

tt <- paintBranches(pruned.tree, edge = sapply(cons, match, pruned.tree$tip.label),
    state = "c*", anc.state = "c")

cols1 <- setNames(c("black", "orange"), c("c", "c*"))

## Body color tree

plot(tt, cols1, ftype = "off", lwd = 2, offset = 0.4)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(tt))

points(pp$xx[1:Ntip(tt)] + 0.02*h, pp$yy[1:Ntip(tt)], pch = 16,
    col = cols1[bodycol[tt$tip.label]], cex = 0.6)

legend("topleft", legend = c("cryptic", "conspicuous"), pch = 21, pt.bg = cols1,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)

cryptic <- readPNG("cryptic.png")
conspicuous <- readPNG("conspicuous.png")

rasterImage(cryptic, 65, 300, 170, 380)
rasterImage(conspicuous, 60, 213, 168, 295)


## Burrowing tree

a <- pruned.data$species[pruned.data$combined_burrow_category == "a"]
t <- pruned.data$species[pruned.data$combined_burrow_category == "t"]

## paint the edges

bt <- paintBranches(pruned.tree, edge = sapply(a, match, pruned.tree$tip.label),
    state = "a", anc.state = "t")

bt

cols2 <- setNames(c("#2F5597", "#956D45"), c("a", "t"))

## Burrowing tree

plot(bt, cols2, ftype = "off", lwd = 2, offset = 0.4, direction = "leftwards")
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(bt))

points(pp$xx[1:Ntip(bt)] - 0.02*h, pp$yy[1:Ntip(bt)], pch = 16,
   col = cols2[burrowing[bt$tip.label]], cex = 0.6)


legend("topright", legend = c("aquatic burrowing", "semi-terrestrial burrowing"), pch = 21, pt.bg = cols2,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)


burrow <- readPNG("burrow3.png")

rasterImage(burrow, 70, 220, 260, 380)



dev.off()


pdf("figure2.pdf")

layout(matrix(c(1, 1, 2, 2,
                1, 1, 3, 3,
                1, 1, 3, 3,
                1, 1, 2, 0,
                1, 1, 2, 2), nrow = 5, ncol = 4, byrow = TRUE))


c <- pruned.data$species[pruned.data$body_color == "c"]
cons <- pruned.data$species[pruned.data$body_color == "c*"]

## paint the edges

tt <- paintBranches(pruned.tree, edge = sapply(cons, match, pruned.tree$tip.label),
    state = "c*", anc.state = "c")

cols1 <- setNames(c("black", "orange"), c("c", "c*"))

## Body color tree

plot(tt, cols1, ftype = "off", lwd = 2, offset = 0.4)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(tt))

points(pp$xx[1:Ntip(tt)] + 0.02*h, pp$yy[1:Ntip(tt)], pch = 16,
    col = cols1[bodycol[tt$tip.label]], cex = 0.6)

legend("topleft", legend = c("cryptic", "conspicuous"), pch = 21, pt.bg = cols1,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)

cryptic <- readPNG("cryptic.png")
conspicuous <- readPNG("conspicuous.png")

rasterImage(cryptic, 65, 300, 170, 380)
rasterImage(conspicuous, 60, 213, 168, 295)


## Burrowing tree

a <- pruned.data$species[pruned.data$combined_burrow_category == "a"]
t <- pruned.data$species[pruned.data$combined_burrow_category == "t"]

## paint the edges

bt <- paintBranches(pruned.tree, edge = sapply(a, match, pruned.tree$tip.label),
    state = "a", anc.state = "t")

bt

cols2 <- setNames(c("#2F5597", "#956D45"), c("a", "t"))

## Burrowing tree

plot(bt, cols2, ftype = "off", lwd = 2, offset = 0.4, direction = "leftwards")
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(bt))

points(pp$xx[1:Ntip(bt)] - 0.02*h, pp$yy[1:Ntip(bt)], pch = 16,
   col = cols2[burrowing[bt$tip.label]], cex = 0.6)


legend("topright", legend = c("aquatic burrowing", "semi-terrestrial burrowing"), pch = 21, pt.bg = cols2,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)


burrow <- readPNG("burrow3.png")

rasterImage(burrow, 70, 220, 260, 380)



dev.off()



```


```{r}


quartz()

layout(matrix(c(1, 1, 1, 2, 2, 2,
                3, 3, 1, 2, 4, 4,
                3, 3, 1, 2, 4, 4,
                3, 3, 1, 2, 5, 5,
                3, 3, 1, 2, 5, 5,
                0, 0, 1, 2, 0, 0,
                1, 1, 1, 2, 2, 2,
                1, 1, 1, 2, 2, 2), nrow = 8, ncol = 6, byrow = TRUE))


## Body color tree

plot(tt, cols1, ftype = "off", lwd = 2, offset = 0.4)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(tt))

points(pp$xx[1:Ntip(tt)] + 0.02*h, pp$yy[1:Ntip(tt)], pch = 16,
    col = cols1[bodycol[tt$tip.label]], cex = 0.6)

legend("topleft", legend = c("cryptic", "conspicuous"), pch = 21, pt.bg = cols1,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)


## Burrowing tree

plot(bt, cols2, ftype = "off", lwd = 2, offset = 0.4, direction = "leftwards")
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(bt))

points(pp$xx[1:Ntip(bt)] - 0.02*h, pp$yy[1:Ntip(bt)], pch = 16,
   col = cols2[burrowing[bt$tip.label]], cex = 0.6)


legend("topright", legend = c("aquatic burrowing", "semi-terrestrial burrowing"), pch = 21, pt.bg = cols2,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)



## Adding pie charts

craydata <- read.csv("col_data.csv", row.names = 1)

craytree <- read.tree("stern.2017.ml.new.tree")
craytree

## Changing levels of the factors "body_color"

craydata$body_color[craydata$body_color == "no"] <- "c"
craydata$body_color[craydata$body_color == "blue"] <- "b"
craydata$body_color[craydata$body_color == "orange"] <- "o"
craydata$body_color[craydata$body_color == "purple"] <- "p"
craydata$body_color[craydata$body_color == "red"] <- "r"
craydata$body_color[craydata$body_color == "blue_red"] <- "g"
craydata$body_color[craydata$body_color == "orange_red"] <- "g"
craydata$body_color[craydata$body_color == "blue_orange_red"] <- "g"
craydata$body_color[craydata$body_color == "blue_purple"] <- "g"
craydata$body_color[craydata$body_color == "unpigmented"] <- "c"


craydata$species <- rownames(craydata)

craydata <- craydata[ , c(19, 1:18)]

unique(craydata$body_color)

craydata$body_color <- as.factor(craydata$body_color)
levels(craydata$body_color)

craydata$combined_burrow_category[craydata$combined_burrow_category == "terrestrial_burrower"] <- "t"
craydata$combined_burrow_category[craydata$combined_burrow_category == "aquatic_burrower"] <- "a"

craydata$combined_burrow_category <- as.factor(craydata$combined_burrow_category)
levels(craydata$combined_burrow_category)

## Pruning the data and tree

chk <- name.check(craytree, craydata)
summary(chk)

pruned.tree <- drop.tip(craytree, chk$tree_not_data)
pruned.data <- craydata[!(rownames(craydata) %in% chk$data_not_tree),, drop = FALSE]
name.check(pruned.tree, pruned.data)

colsf <- setNames(c("skyblue", "#956D45", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))

par(mar = c(5, 2, 2, 0))
pie(table(pruned.data$body_color), border = FALSE, col = colsf, labels = "", radius = 0.5)
text(0, 0.8, paste("Combined \n n = ", length(pruned.data$body_color), sep = ""), font = 2)
legend("left", paste(round((table(pruned.data$body_color)/length(pruned.data$body_color)*100), 1), rep("%", length(unique(pruned.data$body_color)), sep = "")), fill = colsf, bty = "n", cex = 0.8, border = FALSE)

par(mar = c(4, 2, 1.3, 0))
pie(table(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]), border = FALSE, labels = "", main = paste("Aquatic burrowing \n n = ", length(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]), sep = ""), col = colsf, radius = 0.98, cex.main = 0.8)
legend("left", paste(round((table(pruned.data$body_color[pruned.data$combined_burrow_category == "a"])/length(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]))*100, 1), rep("%", length(unique(pruned.data$body_color))), sep = ""), fill = colsf, bty = "n", cex = 0.8, border = FALSE)

pie(table(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]), border = FALSE, main = paste("Semi-terrestrial burrowing \n n = ", length(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]), sep = ""),  col = colsf, labels = "", radius = 0.98, cex.main = 0.8)
legend("left", paste(round((table(pruned.data$body_color[pruned.data$combined_burrow_category == "t"])/length(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]))*100, 1), rep("%", length(unique(pruned.data$body_color))), sep = ""), fill = colsf, bty = "n", cex = 0.8, border = FALSE)


```


```{r, include = FALSE}


png("figure2.1.png", height = 7, width = 7, units = "in", res = 300)


layout(matrix(c(1, 1, 1, 2, 2, 2,
                3, 3, 1, 2, 4, 4,
                3, 3, 1, 2, 4, 4,
                3, 3, 1, 2, 5, 5,
                3, 3, 1, 2, 5, 5,
                0, 0, 1, 2, 0, 0,
                1, 1, 1, 2, 2, 2,
                1, 1, 1, 2, 2, 2), nrow = 8, ncol = 6, byrow = TRUE))


## Body color tree

plot(tt, cols1, ftype = "off", lwd = 2, offset = 0.4)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(tt))

points(pp$xx[1:Ntip(tt)] + 0.02*h, pp$yy[1:Ntip(tt)], pch = 16,
    col = cols1[bodycol[tt$tip.label]], cex = 0.6)

legend("topleft", legend = c("cryptic", "conspicuous"), pch = 21, pt.bg = cols1,
    pt.cex = 1.2, bty = "n", col = "transparent", cex = 1.5)


## Burrowing tree

plot(bt, cols2, ftype = "off", lwd = 2, offset = 0.4, direction = "leftwards")
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(bt))

points(pp$xx[1:Ntip(bt)] - 0.02*h, pp$yy[1:Ntip(bt)], pch = 16,
   col = cols2[burrowing[bt$tip.label]], cex = 0.6)


legend("topright", legend = c("aquatic burrowing", "semi-terrestrial burrowing"), pch = 21, pt.bg = cols2,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)


colsf <- setNames(c("skyblue", "#956D45", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))

par(mar = c(5, 2, 2, 0))
pie(table(pruned.data$body_color), border = FALSE, col = colsf, labels = "", radius = 0.5)
text(0, 0.8, paste("Combined \n n = ", length(pruned.data$body_color), sep = ""), font = 2)
legend("left", paste(round((table(pruned.data$body_color)/length(pruned.data$body_color)*100), 1), rep("%", length(unique(pruned.data$body_color)), sep = "")), fill = colsf, bty = "n", cex = 0.8, border = FALSE)

par(mar = c(4, 2, 1.3, 0))
pie(table(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]), border = FALSE, labels = "", main = paste("Aquatic burrowing \n n = ", length(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]), sep = ""), col = colsf, radius = 0.98, cex.main = 0.8)
legend("left", paste(round((table(pruned.data$body_color[pruned.data$combined_burrow_category == "a"])/length(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]))*100, 1), rep("%", length(unique(pruned.data$body_color))), sep = ""), fill = colsf, bty = "n", cex = 0.8, border = FALSE)

pie(table(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]), border = FALSE, main = paste("Semi-terrestrial burrowing \n n = ", length(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]), sep = ""),  col = colsf, labels = "", radius = 0.98, cex.main = 0.8)
legend("left", paste(round((table(pruned.data$body_color[pruned.data$combined_burrow_category == "t"])/length(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]))*100, 1), rep("%", length(unique(pruned.data$body_color))), sep = ""), fill = colsf, bty = "n", cex = 0.8, border = FALSE)


dev.off()


pdf("figure2.1.pdf")


layout(matrix(c(1, 1, 1, 2, 2, 2,
                3, 3, 1, 2, 4, 4,
                3, 3, 1, 2, 4, 4,
                3, 3, 1, 2, 5, 5,
                3, 3, 1, 2, 5, 5,
                0, 0, 1, 2, 0, 0,
                1, 1, 1, 2, 2, 2,
                1, 1, 1, 2, 2, 2), nrow = 8, ncol = 6, byrow = TRUE))

## Body color tree

plot(tt, cols1, ftype = "off", lwd = 2, offset = 0.4)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(tt))

points(pp$xx[1:Ntip(tt)] + 0.02*h, pp$yy[1:Ntip(tt)], pch = 16,
    col = cols1[bodycol[tt$tip.label]], cex = 0.6)

legend("topleft", legend = c("cryptic", "conspicuous"), pch = 21, pt.bg = cols1,
    pt.cex = 1.2, bty = "n", col = "transparent", cex = 1.5)


## Burrowing tree

plot(bt, cols2, ftype = "off", lwd = 2, offset = 0.4, direction = "leftwards")
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)
h <- max(nodeHeights(bt))

points(pp$xx[1:Ntip(bt)] - 0.02*h, pp$yy[1:Ntip(bt)], pch = 16,
   col = cols2[burrowing[bt$tip.label]], cex = 0.6)


legend("topright", legend = c("aquatic burrowing", "semi-terrestrial burrowing"), pch = 21, pt.bg = cols2,
    pt.cex = 1.5, bty = "n", col = "transparent", cex = 1.5)


par(mar = c(5, 2, 2, 0))
pie(table(pruned.data$body_color), border = FALSE, col = colsf, labels = "", radius = 0.58)
text(0, 0.8, paste("Combined \n n = ", length(pruned.data$body_color), sep = ""), font = 2)
legend("left", paste(round((table(pruned.data$body_color)/length(pruned.data$body_color)*100), 1), rep("%", length(unique(pruned.data$body_color)), sep = "")), fill = colsf, bty = "n", cex = 0.8, border = FALSE)

par(mar = c(4, 2, 1.3, 0))
pie(table(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]), border = FALSE, labels = "", main = paste("Aquatic burrowing \n n = ", length(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]), sep = ""), col = colsf, radius = 0.98, cex.main = 0.8)
legend("left", paste(round((table(pruned.data$body_color[pruned.data$combined_burrow_category == "a"])/length(pruned.data$body_color[pruned.data$combined_burrow_category == "a"]))*100, 1), rep("%", length(unique(pruned.data$body_color))), sep = ""), fill = colsf, bty = "n", cex = 0.8, border = FALSE)

pie(table(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]), border = FALSE, main = paste("Semi-terrestrial burrowing \n n = ", length(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]), sep = ""),  col = colsf, labels = "", radius = 0.98, cex.main = 0.8)
legend("left", paste(round((table(pruned.data$body_color[pruned.data$combined_burrow_category == "t"])/length(pruned.data$body_color[pruned.data$combined_burrow_category == "t"]))*100, 1), rep("%", length(unique(pruned.data$body_color))), sep = ""), fill = colsf, bty = "n", cex = 0.8, border = FALSE)


dev.off()


```



```{r}


craydata <- read.csv("col_data.csv", row.names = 1)

craytree <- read.tree("stern.2017.ml.new.tree")
craytree

## Changing levels of the factors "body_color"

craydata$body_color[craydata$body_color == "no"] <- "c"
craydata$body_color[craydata$body_color == "blue"] <- "b"
craydata$body_color[craydata$body_color == "orange"] <- "o"
craydata$body_color[craydata$body_color == "purple"] <- "p"
craydata$body_color[craydata$body_color == "red"] <- "r"
craydata$body_color[craydata$body_color == "blue_red"] <- "g"
craydata$body_color[craydata$body_color == "orange_red"] <- "g"
craydata$body_color[craydata$body_color == "blue_orange_red"] <- "g"
craydata$body_color[craydata$body_color == "blue_purple"] <- "g"
craydata$body_color[craydata$body_color == "unpigmented"] <- "c"


craydata$species <- rownames(craydata)

craydata <- craydata[ , c(19, 1:18)]

unique(craydata$body_color)

craydata$body_color <- as.factor(craydata$body_color)
levels(craydata$body_color)

craydata$family[craydata$family == "Cambaridea"] <- "Cambaridae"
craydata$family[craydata$family == "Parastacidea"] <- "Parastacidae"
craydata$family[craydata$family == "Astacidea"] <- "Astacidae"
craydata$family[craydata$family == "Cambaroididea"] <- "Cambaroididae"

craydata$family <- as.factor(craydata$family)
levels(craydata$family)

## Pruning the data and tree

chk <- name.check(craytree, craydata)
summary(chk)

pruned.tree <- drop.tip(craytree, chk$tree_not_data)
pruned.data <- craydata[!(rownames(craydata) %in% chk$data_not_tree),, drop = FALSE]
name.check(pruned.tree, pruned.data)

bodycol <- setNames(as.factor(pruned.data$body_color), rownames(pruned.data))
head(bodycol)


## Fan tree

b <- pruned.data$species[pruned.data$body_color == "b"]
c <- pruned.data$species[pruned.data$body_color == "c"]
g <- pruned.data$species[pruned.data$body_color == "g"]
o <- pruned.data$species[pruned.data$body_color == "o"]
p <- pruned.data$species[pruned.data$body_color == "p"]
r <- pruned.data$species[pruned.data$body_color == "r"]

ft <- paintBranches(pruned.tree, edge = sapply(b, match, pruned.tree$tip.label),
    state = "b", anc.state = "c")

ft <- paintBranches(ft, edge = sapply(g, match, pruned.tree$tip.label),
    state = "g")

ft <- paintBranches(ft, edge = sapply(o, match, pruned.tree$tip.label),
    state = "o")

ft <- paintBranches(ft, edge = sapply(p, match, pruned.tree$tip.label),
    state = "p")

ft <- paintBranches(ft, edge = sapply(r, match, pruned.tree$tip.label),
    state = "r")

ft

colsf <- setNames(c("skyblue", "#956D45", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))

plot(ft, colsf, type = "fan", ftype = "off", lwd = 2,
     mar = c(2.5, 2, 2, 1), part = 0.98)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


points(pp$xx[1:Ntip(ft)], pp$yy[1:Ntip(ft)], pch = 16,
   col = colsf[bodycol[ft$tip.label]], cex = 0.7)

text(scale, rep(-23, length(scale)), h - scale, cex = 0.6)
text(mean(scale), -38, "time (mya)", cex = 0.7)

legend("bottomleft", legend = c("blue", "cryptic", "polymorphic", "orange", "purple", "red"), pch = 21, pt.bg = colsf,
    pt.cex = 0.9, bty = "n", col = "transparent", cex = 0.8)

unique(pruned.data$family)

Cambaridae <- pruned.data$species[pruned.data$family == "Cambaridae"]
Parastacidae <- pruned.data$species[pruned.data$family == "Parastacidae"]
Astacidae <- pruned.data$species[pruned.data$family == "Astacidae"]
Cambaroididae <- pruned.data$species[pruned.data$family == "Cambaroididae"]


node1 <- getMRCA(ft, Cambaridae)
node2 <- getMRCA(ft, Parastacidae)
node3 <- getMRCA(ft, Astacidae)
node4 <- getMRCA(ft, Cambaroididae)

nodes <- c(node1, node2, node3, node4)
nodes

labels <- as.character(unique(pruned.data$family))

for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.05, lab.offset = 1.1, mark.node = FALSE, lwd = 3, 
                    orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                    "horizontal" else "curved")


colsf2 <- setNames(c("skyblue", "black", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))


plot(ft, colsf2, type = "fan", ftype = "off", lwd = 2,
     mar = c(2.5, 2, 2, 1), part = 0.98)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)


for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}

points(pp$xx[1:Ntip(ft)], pp$yy[1:Ntip(ft)], pch = 16,
   col = colsf2[bodycol[ft$tip.label]], cex = 0.7)

text(scale, rep(-23, length(scale)), h - scale, cex = 0.6)
text(mean(scale), -38, "time (mya)", cex = 0.7)

legend("bottomleft", legend = c("blue", "cryptic", "polymorphic", "orange", "purple", "red"), pch = 21, pt.bg = colsf,
    pt.cex = 0.9, bty = "n", col = "transparent", cex = 0.8)

for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.05, lab.offset = 1.1, mark.node = FALSE, lwd = 3, 
                    orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                    "horizontal" else "curved")



## Adding different colors to polymorphic species

craydata <- read.csv("col_data.csv", row.names = 1)
poly <- craydata

craytree <- read.tree("stern.2017.ml.new.tree")
craytree

## Changing levels of the factors "body_color"

poly$body_color[poly$body_color == "no"] <- "c"
poly$body_color[poly$body_color == "blue"] <- "b"
poly$body_color[poly$body_color == "orange"] <- "o"
poly$body_color[poly$body_color == "purple"] <- "p"
poly$body_color[poly$body_color == "red"] <- "r"
poly$body_color[poly$body_color == "blue_red"] <- "b+r"
poly$body_color[poly$body_color == "orange_red"] <- "o+r"
poly$body_color[poly$body_color == "blue_orange_red"] <- "b+o+r"
poly$body_color[poly$body_color == "blue_purple"] <- "b+p"
poly$body_color[poly$body_color == "unpigmented"] <- "c"


poly$species <- rownames(poly)

poly <- poly[ , c(19, 1:18)]

unique(poly$body_color)

poly$body_color <- as.factor(poly$body_color)
levels(poly$body_color)

## Pruning the data and tree

chk <- name.check(craytree, poly)
summary(chk)

poly.tree <- drop.tip(craytree, chk$tree_not_data)
poly.data <- poly[!(rownames(poly) %in% chk$data_not_tree),, drop = FALSE]
name.check(poly.tree, poly.data)

polycol <- setNames(as.factor(poly.data$body_color), rownames(poly.data))
head(polycol)

br <- poly$species[poly$body_color == "b+r"]
or <- poly$species[poly$body_color == "o+r"]
bor <- poly$species[poly$body_color == "b+o+r"]
bp <- poly$species[poly$body_color == "b+p"]


pies <- matrix(0, Ntip(poly.tree), 5,
	 dimnames = list(pruned.tree$tip.label, c("b", "c", "o", "p", "r")))

pies[b, "b"] <- 1
pies[c, "c"] <- 1
pies[br, c("b", "r")] <- 0.5
pies[or, c("o", "r")] <- 0.5
pies[bor, c("b", "o", "r")] <- 1/3
pies[bp, c("b", "p")] <- 0.5
pies[o, "o"] <- 1
pies[p, "p"] <- 1
pies[r, "r"] <- 1


colsp <- setNames(c("skyblue", "black", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))

plot(ft, colsp, type = "fan", ftype = "off", lwd = 2,
     mar = c(2.5, 2, 2, 1), part = 0.98)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

text(scale, rep(-23, length(scale)), h - scale, cex = 0.6)
text(mean(scale), -38, "time (mya)", cex = 0.7)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


par(fg = "transparent")
colspie <- setNames(c("skyblue", "black", "orange", "#6600CC", "red"), c("b", "c", "o", "p", "r"))

tiplabels(pie = pies, piecol = colspie, cex = 0.22)

par(fg = "black")
legend("bottomleft", legend = c("blue", "cryptic", "orange", "purple", "red"), pch = 21, pt.bg = colspie,
    pt.cex = 0.9, bty = "n", col = "transparent", cex = 0.8)


for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.05, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 3, 
                    orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                    "horizontal" else "curved")




spp <- c("Euastacus_australasiensis", "Engaeus_cymus", "Cambarus_dubius", "Cambarus_harti", "Cherax_robustus", 
         "Distocambarus_carlsoni", "Faxonius_rusticus", "Procambarus_clarkii")

nodes2 <- sapply(spp, grep, x = ft$tip.label)
nodes2

labels2 <- LETTERS[1:length(spp)]

Australasiensis <- readPNG("imgs/Euastacus_australasiensis.png")
Engaeus <- readPNG("imgs/Engaeus_cymus.png")
Dubius <- readPNG("imgs/Cambarus_dubius.png")
Cambarus <- readPNG("imgs/Cambarus_harti.png")
Cherax <- readPNG("imgs/Cherax_robustus.png")
Distocambarus <- readPNG("imgs/Distocambarus_carlsoni.png")
Faxonius <- readPNG("imgs/Faxonius_rusticus.png")
Procambarus <- readPNG("imgs/Procambarus_clarkii.png")


plot(ft, plot = FALSE)
rasterImage(Australasiensis, -25, 40, 120, 100)
rasterImage(Engaeus, 120, 40, 245, 100)
rasterImage(Dubius, 245, 40, 370, 100)
rasterImage(Cambarus, 370, 40, 495, 100)
rasterImage(Cherax, -25, -18, 120, 40)
rasterImage(Distocambarus, 120, -18, 245, 40)
rasterImage(Faxonius, 245, -18, 370, 40)
rasterImage(Procambarus, 370, -18, 495, 40)

points(-6, 90, bg = "red", pch = 21, cex = 3)
text(-6, 90, "A")
points(135, 90, bg = "orange", pch = 21, cex = 3)
text(135, 90, "B")
points(260, 90, bg = "skyblue", pch = 21, cex = 3)
text(260, 90, "C")
points(385, 90, bg = "skyblue", pch = 21, cex = 3)
text(385, 90, "D")
points(-6, 30, bg = "purple", pch = 21, cex = 3)
text(-6, 30, "E")
points(135, 30, bg = "orange", pch = 21, cex = 3)
text(135, 30, "F")
points(260, 30, bg = "#956D45", pch = 21, cex = 3)
text(260, 30, "G")
points(385, 30, bg = "red", pch = 21, cex = 3)
text(385, 30, "H")


legend("topleft", legend = c("blue", "cryptic", "orange", "purple", "red"), pch = 21, pt.bg = colspie,
    pt.cex = 0.7, bty = "n", col = "transparent", cex = 0.7)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(10, 4, 1, 4), part = 0.96)

par(fg = "black")

for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.065, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 1.5, col = "black", cex = 0.7, orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                                 "horizontal" else "curved")

nodelabels(LETTERS[1:length(nodes2)], node = nodes2, frame = "circle", bg = c("red", "orange", "skyblue", "skyblue", "purple",
                                                                              "orange", "#956D45", "red"), cex = 1)

par(new = TRUE)

plot(ft, colsp, type = "fan", ftype = "off", mar = c(12, 6, 3, 6), part = 0.96)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

text(scale, rep(-28, length(scale)), h - scale, cex = 0.5, srt = 20)
text(mean(scale), -48, "time (mya)", cex = 0.5)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


par(fg = "transparent")

colspie <- setNames(c("skyblue", "black", "orange", "#6600CC", "red"), c("b", "c", "o", "p", "r"))

tiplabels(pie = pies, piecol = colspie, cex = 0.2)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(11.8, 5.8, 2.8, 5.8), part = 0.96)

par(fg = "black")

for(i in 1:length(nodes2)){
    xy <- add.arrow(ft, nodes2[i], col = "blue", arrl = 20, lwd = 1.5, hedl = 5, offset = 2)
}






plot(ft, plot = FALSE)
rasterImage(Australasiensis, -25, 40, 120, 100)
rasterImage(Engaeus, 120, 40, 245, 100)
rasterImage(Dubius, 245, 40, 370, 100)
rasterImage(Cambarus, 370, 40, 495, 100)
rasterImage(Cherax, -25, -18, 120, 40)
rasterImage(Distocambarus, 120, -18, 245, 40)
rasterImage(Faxonius, 245, -18, 370, 40)
rasterImage(Procambarus, 370, -18, 495, 40)

points(-6, 90, bg = "red", pch = 21, cex = 3)
text(-6, 90, "A")
points(135, 90, bg = "orange", pch = 21, cex = 3)
text(135, 90, "B")
points(260, 90, bg = "skyblue", pch = 21, cex = 3)
text(260, 90, "C")
points(385, 90, bg = "skyblue", pch = 21, cex = 3)
text(385, 90, "D")
points(-6, 30, bg = "purple", pch = 21, cex = 3)
text(-6, 30, "E")
points(135, 30, bg = "orange", pch = 21, cex = 3)
text(135, 30, "F")
points(260, 30, bg = "#956D45", pch = 21, cex = 3)
text(260, 30, "G")
points(385, 30, bg = "red", pch = 21, cex = 3)
text(385, 30, "H")


legend("topleft", legend = c("blue", "cryptic", "orange", "purple", "red"), pch = 21, pt.bg = colspie,
    pt.cex = 0.7, bty = "n", col = "transparent", cex = 0.7)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(10, 4, 1, 4), part = 0.96)

par(fg = "black")


nodelabels(LETTERS[1:length(nodes2)], node = nodes2, frame = "circle", bg = c("red", "orange", "skyblue", "skyblue", "purple",
                                                                              "orange", "#956D45", "red"), cex = 1)

obj <- get("last_plot.phylo", envir = .PlotPhyloEnv)

par(new = TRUE)

plot(ft, colsp, type = "fan", ftype = "off", mar = c(11, 5, 2, 5), part = 0.96)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

text(scale, rep(-28, length(scale)), h - scale, cex = 0.5, srt = 20)
text(mean(scale), -48, "time (mya)", cex = 0.5)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


par(fg = "transparent")

colspie <- setNames(c("skyblue", "black", "orange", "#6600CC", "red"), c("b", "c", "o", "p", "r"))

tiplabels(pie = pies, piecol = colspie, cex = 0.2)

par(fg = "black")


```


```{r, include = FALSE}

quartz()

png("figure5.1.png", height = 7, width = 7, units = "in", res = 300)

plot(ft, plot = FALSE)
rasterImage(Australasiensis, -25, 40, 120, 100)
rasterImage(Engaeus, 120, 40, 245, 100)
rasterImage(Dubius, 245, 40, 370, 100)
rasterImage(Cambarus, 370, 40, 495, 100)
rasterImage(Cherax, -25, -18, 120, 40)
rasterImage(Distocambarus, 120, -18, 245, 40)
rasterImage(Faxonius, 245, -18, 370, 40)
rasterImage(Procambarus, 370, -18, 495, 40)

points(-6, 90, bg = "red", pch = 21, cex = 3)
text(-6, 90, "A")
points(135, 90, bg = "orange", pch = 21, cex = 3)
text(135, 90, "B")
points(260, 90, bg = "skyblue", pch = 21, cex = 3)
text(260, 90, "C")
points(385, 90, bg = "skyblue", pch = 21, cex = 3)
text(385, 90, "D")
points(-6, 30, bg = "purple", pch = 21, cex = 3)
text(-6, 30, "E")
points(135, 30, bg = "orange", pch = 21, cex = 3)
text(135, 30, "F")
points(260, 30, bg = "#956D45", pch = 21, cex = 3)
text(260, 30, "G")
points(385, 30, bg = "red", pch = 21, cex = 3)
text(385, 30, "H")


legend("topleft", legend = c("blue", "cryptic", "orange", "purple", "red"), pch = 21, pt.bg = colspie,
    pt.cex = 0.7, bty = "n", col = "transparent", cex = 0.7)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(10, 4, 1, 4), part = 0.96)

par(fg = "black")

for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.065, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 1.5, col = "black", cex = 0.7, orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                                 "horizontal" else "curved")

nodelabels(LETTERS[1:length(nodes2)], node = nodes2, frame = "circle", bg = c("red", "orange", "skyblue", "skyblue", "purple",
                                                                              "orange", "#956D45", "red"), cex = 1)

par(new = TRUE)

plot(ft, colsp, type = "fan", ftype = "off", mar = c(12, 6, 3, 6), part = 0.96)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

text(scale, rep(-28, length(scale)), h - scale, cex = 0.5, srt = 20)
text(mean(scale), -48, "time (mya)", cex = 0.5)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


par(fg = "transparent")

colspie <- setNames(c("skyblue", "black", "orange", "#6600CC", "red"), c("b", "c", "o", "p", "r"))

tiplabels(pie = pies, piecol = colspie, cex = 0.2)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(11.8, 5.8, 2.8, 5.8), part = 0.96)

par(fg = "black")

for(i in 1:length(nodes2)){
    xy <- add.arrow(ft, nodes2[i], col = "blue", arrl = 20, lwd = 1.5, hedl = 5, offset = 2)
}


dev.off()



quartz()

pdf("figure5.1.pdf")


plot(ft, plot = FALSE)
rasterImage(Australasiensis, -25, 40, 120, 100)
rasterImage(Engaeus, 120, 40, 245, 100)
rasterImage(Dubius, 245, 40, 370, 100)
rasterImage(Cambarus, 370, 40, 495, 100)
rasterImage(Cherax, -25, -18, 120, 40)
rasterImage(Distocambarus, 120, -18, 245, 40)
rasterImage(Faxonius, 245, -18, 370, 40)
rasterImage(Procambarus, 370, -18, 495, 40)

points(-6, 90, bg = "red", pch = 21, cex = 3)
text(-6, 90, "A")
points(135, 90, bg = "orange", pch = 21, cex = 3)
text(135, 90, "B")
points(260, 90, bg = "skyblue", pch = 21, cex = 3)
text(260, 90, "C")
points(385, 90, bg = "skyblue", pch = 21, cex = 3)
text(385, 90, "D")
points(-6, 30, bg = "purple", pch = 21, cex = 3)
text(-6, 30, "E")
points(135, 30, bg = "orange", pch = 21, cex = 3)
text(135, 30, "F")
points(260, 30, bg = "#956D45", pch = 21, cex = 3)
text(260, 30, "G")
points(385, 30, bg = "red", pch = 21, cex = 3)
text(385, 30, "H")


legend("topleft", legend = c("blue", "cryptic", "orange", "purple", "red"), pch = 21, pt.bg = colspie,
    pt.cex = 0.7, bty = "n", col = "transparent", cex = 0.7)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(10, 4, 1, 4), part = 0.96)

par(fg = "black")

for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.065, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 1.5, col = "black", cex = 0.7, orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                                 "horizontal" else "curved")

nodelabels(LETTERS[1:length(nodes2)], node = nodes2, frame = "circle", bg = c("red", "orange", "skyblue", "skyblue", "purple",
                                                                              "orange", "#956D45", "red"), cex = 1)

par(new = TRUE)

plot(ft, colsp, type = "fan", ftype = "off", mar = c(12, 6, 3, 6), part = 0.96)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

text(scale, rep(-28, length(scale)), h - scale, cex = 0.5, srt = 20)
text(mean(scale), -48, "time (mya)", cex = 0.5)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


par(fg = "transparent")

colspie <- setNames(c("skyblue", "black", "orange", "#6600CC", "red"), c("b", "c", "o", "p", "r"))

tiplabels(pie = pies, piecol = colspie, cex = 0.2)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(11.8, 5.8, 2.8, 5.8), part = 0.96)

par(fg = "black")

for(i in 1:length(nodes2)){
    xy <- add.arrow(ft, nodes2[i], col = "blue", arrl = 20, lwd = 1.5, hedl = 5, offset = 2)
}


dev.off()


quartz()


png("figure5.2.png", height = 7, width = 7, units = "in", res = 300)


plot(ft, plot = FALSE)
rasterImage(Australasiensis, -25, 40, 120, 100)
rasterImage(Engaeus, 120, 40, 245, 100)
rasterImage(Dubius, 245, 40, 370, 100)
rasterImage(Cambarus, 370, 40, 495, 100)
rasterImage(Cherax, -25, -18, 120, 40)
rasterImage(Distocambarus, 120, -18, 245, 40)
rasterImage(Faxonius, 245, -18, 370, 40)
rasterImage(Procambarus, 370, -18, 495, 40)

points(-6, 90, bg = "red", pch = 21, cex = 3)
text(-6, 90, "A")
points(135, 90, bg = "orange", pch = 21, cex = 3)
text(135, 90, "B")
points(260, 90, bg = "skyblue", pch = 21, cex = 3)
text(260, 90, "C")
points(385, 90, bg = "skyblue", pch = 21, cex = 3)
text(385, 90, "D")
points(-6, 30, bg = "purple", pch = 21, cex = 3)
text(-6, 30, "E")
points(135, 30, bg = "orange", pch = 21, cex = 3)
text(135, 30, "F")
points(260, 30, bg = "#956D45", pch = 21, cex = 3)
text(260, 30, "G")
points(385, 30, bg = "red", pch = 21, cex = 3)
text(385, 30, "H")


legend("topleft", legend = c("blue", "cryptic", "orange", "purple", "red"), pch = 21, pt.bg = colspie,
    pt.cex = 0.7, bty = "n", col = "transparent", cex = 0.7)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(10, 4, 1, 4), part = 0.96)

par(fg = "black")


nodelabels(LETTERS[1:length(nodes2)], node = nodes2, frame = "circle", bg = c("red", "orange", "skyblue", "skyblue", "purple",
                                                                              "orange", "#956D45", "red"), cex = 1)

par(new = TRUE)

plot(ft, colsp, type = "fan", ftype = "off", mar = c(11, 5, 2, 5), part = 0.96)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

text(scale, rep(-28, length(scale)), h - scale, cex = 0.5)
text(mean(scale), -48, "time (mya)", cex = 0.5)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


par(fg = "transparent")

colspie <- setNames(c("skyblue", "black", "orange", "#6600CC", "red"), c("b", "c", "o", "p", "r"))

tiplabels(pie = pies, piecol = colspie, cex = 0.2)

par(fg = "black")

dev.off()


quartz()

pdf("figure5.2.pdf")


plot(ft, plot = FALSE)
rasterImage(Australasiensis, -25, 40, 120, 100)
rasterImage(Engaeus, 120, 40, 245, 100)
rasterImage(Dubius, 245, 40, 370, 100)
rasterImage(Cambarus, 370, 40, 495, 100)
rasterImage(Cherax, -25, -18, 120, 40)
rasterImage(Distocambarus, 120, -18, 245, 40)
rasterImage(Faxonius, 245, -18, 370, 40)
rasterImage(Procambarus, 370, -18, 495, 40)

points(-6, 90, bg = "red", pch = 21, cex = 3)
text(-6, 90, "A")
points(135, 90, bg = "orange", pch = 21, cex = 3)
text(135, 90, "B")
points(260, 90, bg = "skyblue", pch = 21, cex = 3)
text(260, 90, "C")
points(385, 90, bg = "skyblue", pch = 21, cex = 3)
text(385, 90, "D")
points(-6, 30, bg = "purple", pch = 21, cex = 3)
text(-6, 30, "E")
points(135, 30, bg = "orange", pch = 21, cex = 3)
text(135, 30, "F")
points(260, 30, bg = "#956D45", pch = 21, cex = 3)
text(260, 30, "G")
points(385, 30, bg = "red", pch = 21, cex = 3)
text(385, 30, "H")


legend("topleft", legend = c("blue", "cryptic", "orange", "purple", "red"), pch = 21, pt.bg = colspie,
    pt.cex = 0.7, bty = "n", col = "transparent", cex = 0.7)

par(new = TRUE)

par(fg = "transparent")

plot(ft, "white", type = "fan", ftype = "off", mar = c(10, 4, 1, 4), part = 0.96)

par(fg = "black")


nodelabels(LETTERS[1:length(nodes2)], node = nodes2, frame = "circle", bg = c("red", "orange", "skyblue", "skyblue", "purple",
                                                                              "orange", "#956D45", "red"), cex = 1)


par(new = TRUE)

plot(ft, colsp, type = "fan", ftype = "off", mar = c(11, 5, 2, 5), part = 0.96)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

text(scale, rep(-28, length(scale)), h - scale, cex = 0.5)
text(mean(scale), -48, "time (mya)", cex = 0.5)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}


par(fg = "transparent")

colspie <- setNames(c("skyblue", "black", "orange", "#6600CC", "red"), c("b", "c", "o", "p", "r"))

tiplabels(pie = pies, piecol = colspie, cex = 0.2)

par(fg = "black")

dev.off()




```


```{r, eval = FALSE, include = FALSE}


## ggtree function

pies[b, "b"] <- "b"
pies[c, "c"] <- "c"
pies[br, c("b", "r")] <- c("b", "r")
pies[or, c("o", "r")] <- c("o", "r")
pies[bor, c("b", "o", "r")] <- c("b", "o", "r")
pies[bp, c("b", "p")] <- c("b", "p")
pies[o, "o"] <- "o"
pies[p, "p"] <- "p"
pies[r, "r"] <- "r"
pies[pies == "0"] <- "c"

colors <- c("blue", "black", "orange", "purple", "red")

gt <- ggtree(ft, layout = "circular", colour = "black")

p1 <- gheatmap(gt, pies, offset = 0, width = .05,
               colnames = FALSE, colnames_offset_y = 0, color = "black") + scale_fill_manual(values = colors, name = "body color", guide = guide_legend(keywidth = 0.5, keyheight = 0.5, order = 6, title = "body color"))


```


```{r, include = FALSE}


png("figure3.png", height = 7, width = 7, units = "in", res = 300)

colsf <- setNames(c("skyblue", "#956D45", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))

plot(ft, colsf, type = "fan", ftype = "off", lwd = 2,
     mar = c(2.5, 2, 2, 1), part = 0.98)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}

points(pp$xx[1:Ntip(ft)], pp$yy[1:Ntip(ft)], pch = 16,
   col = colsf[bodycol[ft$tip.label]], cex = 0.7)

text(scale, rep(-23, length(scale)), h - scale, cex = 0.6)
text(mean(scale), -38, "time (mya)", cex = 0.7)


for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.05, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 3, 
                    orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                    "horizontal" else "curved")

legend("bottomleft", legend = c("blue", "cryptic", "polymorphic", "orange", "purple", "red"), pch = 21, pt.bg = colsf,
    pt.cex = 0.9, bty = "n", col = "transparent", cex = 0.8)



dev.off()



pdf("figure3.pdf")


colsf <- setNames(c("skyblue", "#956D45", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))


plot(ft, colsf, type = "fan", ftype = "off", lwd = 2,
     mar = c(2.5, 2, 2, 1), part = 0.98)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}

points(pp$xx[1:Ntip(ft)], pp$yy[1:Ntip(ft)], pch = 16,
   col = colsf[bodycol[ft$tip.label]], cex = 0.7)

text(scale, rep(-23, length(scale)), h - scale, cex = 0.6)
text(mean(scale), -38, "time (mya)", cex = 0.7)


legend("bottomleft", legend = c("blue", "cryptic", "polymorphic", "orange", "purple", "red"), pch = 21, pt.bg = colsf,
    pt.cex = 0.9, bty = "n", col = "transparent", cex = 0.8)


for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.05, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 3, 
                    orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                    "horizontal" else "curved")


dev.off()


png("figure4.png", height = 7, width = 7, units = "in", res = 300)

colsf2 <- setNames(c("skyblue", "black", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))


plot(ft, colsf2, type = "fan", ftype = "off", lwd = 2,
     mar = c(2.5, 2, 2, 1), part = 0.98)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}

points(pp$xx[1:Ntip(ft)], pp$yy[1:Ntip(ft)], pch = 16,
   col = colsf2[bodycol[ft$tip.label]], cex = 0.7)

text(scale, rep(-23, length(scale)), h - scale, cex = 0.6)
text(mean(scale), -38, "time (mya)", cex = 0.7)


legend("bottomleft", legend = c("blue", "cryptic", "polymorphic", "orange", "purple", "red"), pch = 21, pt.bg = colsf,
    pt.cex = 0.9, bty = "n", col = "transparent", cex = 0.8)

for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.05, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 3, 
                    orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                    "horizontal" else "curved")


dev.off()


pdf("figure4.pdf")

colsf2 <- setNames(c("skyblue", "black", "green4", "orange", "#6600CC", "red"), c("b", "c", "g", "o", "p", "r"))


plot(ft, colsf2, type = "fan", ftype = "off", lwd = 2,
     mar = c(2.5, 2, 2, 1), part = 0.98)

h <- max(nodeHeights(ft))
tick.spacing <- 20
min.tick <- 0
scale <- axis(1, pos = -5, at = seq(h, min.tick, by = -tick.spacing), cex.axis = 0.5, labels = FALSE)
pp <- get("last_plot.phylo", envir = .PlotPhyloEnv)

for(i in 1:length(scale)){
    a1 <- 0
    a2 <- 2*pi
    draw.arc(0, 0, radius = scale[i], a1, a2, lwd = 1,
        col = make.transparent("blue", 0.15))
}

points(pp$xx[1:Ntip(ft)], pp$yy[1:Ntip(ft)], pch = 16,
   col = colsf2[bodycol[ft$tip.label]], cex = 0.7)

text(scale, rep(-23, length(scale)), h - scale, cex = 0.6)
text(mean(scale), -38, "time (mya)", cex = 0.7)

legend("bottomleft", legend = c("blue", "cryptic", "polymorphic", "orange", "purple", "red"), pch = 21, pt.bg = colsf,
       pt.cex = 0.9, bty = "n", col = "transparent", cex = 0.8)

for(i in 1:length(nodes)) 
    arc.cladelabels(text = labels[i], node = nodes[i], ln.offset = 1.05, lab.offset = 1.1, mark.node = FALSE,
                    lwd = 3, 
                    orientation = if(labels[i] %in% c("Astacidae", "Cambaroididae"))
                                    "horizontal" else "curved")


dev.off()


```



```{r, eval = FALSE, include = FALSE}


quartz()

png("figure6.png", height = 7, width = 7, units = "in", res = 300)

print(p1)

dev.off()

pdf("figure6.pdf")

print(p1)

dev.off()


```
